ThongKe/ThongKe.Web/Controllers/BaoCaoController.cs
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using ThongKe.Data.Repositories;
using ThongKe.Service;
using ThongKe.Web.Infrastructure.Core;
using System.Web.Script.Serialization;
using ThongKe.Data.Models.EF;
using ThongKe.Web.Infrastructure.Extensions;
using ThongKe.Web.Models;
using Newtonsoft.Json;
using AutoMapper;
using System.Text;
using System.Text.RegularExpressions;

namespace ThongKe.Web.Controllers
{
    public class BaoCaoController : BaseController
    {
        private IThongKeService _thongkeService;
        private IaccountService _accountService;
        private ICommonService _commonService;
        public BaoCaoController(IThongKeService thongKeService)
        {
            _thongkeService = thongKeService;

        }
        // GET: BaoCao
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SaleTheoQuay()
        {
            return View();
        }//

        public ActionResult KinhDoanhOnline()
        {
            return View();
        }//
        public ActionResult KinhDoanhOnline_ngaydi()
        {
            return View();
        }
        [HttpPost]
        public ViewResult SaleTheoQuay(string tungay, string denngay, string chinhanh, string khoi)//(string tungay,string denngay, string daily)
        {
            chinhanh = String.IsNullOrEmpty(chinhanh) ? Session["chinhanh"].ToString() : chinhanh;
            khoi = String.IsNullOrEmpty(khoi) ? Session["khoi"].ToString() : khoi;
            string fromTo = "";
            ExcelPackage ExcelApp = new ExcelPackage();
            ExcelWorksheet xlSheet = ExcelApp.Workbook.Worksheets.Add("Report");
            // Định dạng chiều dài cho cột
            xlSheet.Column(1).Width = 10;//stt
            xlSheet.Column(2).Width = 50;// sales
            xlSheet.Column(3).Width = 10;//stt
            xlSheet.Column(4).Width = 30;// doanh so
            xlSheet.Column(5).Width = 30;// doanh thu sale

            xlSheet.Cells[2, 1].Value = "BÁO CÁO DOANH THU THEO NGÀY BÁN QUẦY " + khoi + " " + chinhanh;
            xlSheet.Cells[2, 1].Style.Font.SetFromFont(new Font("Times New Roman", 16, FontStyle.Bold));
            xlSheet.Cells[2, 1, 2, 5].Merge = true;
            setCenterAligment(2, 1, 2, 5, xlSheet);
            // dinh dang tu ngay den ngay
            if (tungay == denngay)
            {
                fromTo = "Ngày: " + tungay;
            }
            else
            {
                fromTo = "Từ ngày: " + tungay + " đến ngày: " + denngay;
            }
            xlSheet.Cells[3, 1].Value = fromTo;
            xlSheet.Cells[3, 1, 3, 5].Merge = true;
            xlSheet.Cells[3, 1].Style.Font.SetFromFont(new Font("Times New Roman", 14, FontStyle.Bold));
            setCenterAligment(3, 1, 3, 5, xlSheet);

            // Tạo header
            xlSheet.Cells[5, 1].Value = "STT";
            xlSheet.Cells[5, 2].Value = "Nhân viên ";
            xlSheet.Cells[5, 3].Value = "Code chinhanh ";

            xlSheet.Cells[5, 4].Value = "Tổng tiền";
            xlSheet.Cells[5, 5].Value = "Doanh số";

            xlSheet.Cells[5, 1, 5, 5].Style.Font.SetFromFont(new Font("Times New Roman", 12, FontStyle.Bold));

            // do du lieu tu table  
            int dong = 5;


            DataTable dt = _thongkeService.doanhthuSaleTheoQuay(tungay, denngay, chinhanh, khoi);// Session["daily"].ToString(), Session["khoi"].ToString());

            if (dt != null)
            {
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    dong++;
                    for (int j = 0; j < dt.Columns.Count; j++)
                    {
                        if (String.IsNullOrEmpty(dt.Rows[i][j].ToString()))
                        {
                            xlSheet.Cells[dong, j + 1].Value = "";
                        }
                        else
                        {
                            xlSheet.Cells[dong, j + 1].Value = dt.Rows[i][j];
                        }
                    }
                }
            }
            else
            {
                SetAlert("No sale.", "warning");
                return View();
            }

            dong++;
            //// Merger cot 4,5 ghi tổng tiền
            //setRightAligment(dong, 3, dong, 3, xlSheet);
            //xlSheet.Cells[dong, 1, dong, 2].Merge = true;
            //xlSheet.Cells[dong, 1].Value = "Tổng tiền: ";
            // Sum tổng tiền
            xlSheet.Cells[dong, 4].Formula = "SUM(D6:D" + (6 + dt.Rows.Count - 1) + ")";
            xlSheet.Cells[dong, 5].Formula = "SUM(E6:E" + (6 + dt.Rows.Count - 1) + ")";


            setBorder(5, 1, 5 + dt.Rows.Count, 5, xlSheet);
            setFontBold(5, 1, 5, 5, 11, xlSheet);
            setFontSize(6, 1, 6 + dt.Rows.Count, 5, 11, xlSheet);
            // canh giua cot stt
            setCenterAligment(6, 1, 6 + dt.Rows.Count, 1, xlSheet);
            // canh giua code chinhanh
            setCenterAligment(6, 3, 6 + dt.Rows.Count, 3, xlSheet);
            NumberFormat(6, 4, 6 + dt.Rows.Count, 5, xlSheet);
            // định dạng số cot tong cong
            NumberFormat(dong, 4, dong, 5, xlSheet);
            setBorder(dong, 4, dong, 5, xlSheet);
            setFontBold(dong, 4, dong, 5, 12, xlSheet);

            //xlSheet.View.FreezePanes(6, 20);


            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            //Response.AddHeader("Content-Disposition", "attachment; filename=" + "DoanhThuQuay_" + Session["daily"].ToString() + "_" + System.DateTime.Now.ToString("dd/MM/yyyy HH:mm") + ".xlsx");
            Response.AddHeader("Content-Disposition", "attachment; filename=" + "DoanhThuSale_" + khoi + " " + chinhanh + "_" + System.DateTime.Now.ToString("dd/MM/yyyy HH:mm") + ".xlsx");
            Response.BinaryWrite(ExcelApp.GetAsByteArray());
            Response.End();

            return View();
        }

        public ViewResult SaleTheoNgayDi()
        {

            return View();
        }//

        [HttpPost]
        public ViewResult SaleTheoNgayDi(string tungay, string denngay, string chinhanh, string khoi)
        {
            // cn = Session["chinhanh"].ToString();
            khoi = String.IsNullOrEmpty(khoi) ? Session["khoi"].ToString() : khoi;
            string fromTo = "";
            ExcelPackage ExcelApp = new ExcelPackage();
            ExcelWorksheet xlSheet = ExcelApp.Workbook.Worksheets.Add("Report");
            // Định dạng chiều dài cho cột
            xlSheet.Column(1).Width = 10;//stt
            xlSheet.Column(2).Width = 50;// sales
            xlSheet.Column(3).Width = 10;// code cn
            xlSheet.Column(4).Width = 30;// doanh so
            xlSheet.Column(5).Width = 30;// doanh thu sale

            xlSheet.Cells[2, 1].Value = "BÁO CÁO DOANH THU THEO NGÀY ĐI SALE " + khoi + " " + chinhanh;
            xlSheet.Cells[2, 1].Style.Font.SetFromFont(new Font("Times New Roman", 16, FontStyle.Bold));
            xlSheet.Cells[2, 1, 2, 5].Merge = true;
            setCenterAligment(2, 1, 2, 5, xlSheet);
            // dinh dang tu ngay den ngay
            if (tungay == denngay)
            {
                fromTo = "Ngày: " + tungay;
            }
            else
            {
                fromTo = "Từ ngày: " + tungay + " đến ngày: " + denngay;
            }
            xlSheet.Cells[3, 1].Value = fromTo;
            xlSheet.Cells[3, 1, 3, 5].Merge = true;
            xlSheet.Cells[3, 1].Style.Font.SetFromFont(new Font("Times New Roman", 14, FontStyle.Bold));
            setCenterAligment(3, 1, 3, 5, xlSheet);

            // Tạo header
            xlSheet.Cells[5, 1].Value = "STT";
            xlSheet.Cells[5, 2].Value = "Nhân viên ";
            xlSheet.Cells[5, 3].Value = "Code CN ";

            xlSheet.Cells[5, 4].Value = "Tổng tiền";
            xlSheet.Cells[5, 5].Value = "Doanh số";

            xlSheet.Cells[5, 1, 5, 5].Style.Font.SetFromFont(new Font("Times New Roman", 12, FontStyle.Bold));

            // do du lieu tu table
            int dong = 5;


            DataTable dt = new DataTable();
            dt = _thongkeService.doanhthuSaleTheoNgayDi(tungay, denngay, chinhanh, khoi);// Session["daily"].ToString(), Session["khoi"].ToString());

            if (dt != null)
            {
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    dong++;
                    for (int j = 0; j < dt.Columns.Count; j++)
                    {
                        if (String.IsNullOrEmpty(dt.Rows[i][j].ToString()))
                        {
                            xlSheet.Cells[dong, j + 1].Value = "";
                        }
                        else
                        {
                            xlSheet.Cells[dong, j + 1].Value = dt.Rows[i][j];
                        }
                    }
                }
            }
            else
            {
                SetAlert("No sale.", "warning");
                return View();
            }

            dong++;
            //// Merger cot 4,5 ghi tổng tiền
            //setRightAligment(dong, 3, dong, 3, xlSheet);
            //xlSheet.Cells[dong, 1, dong, 2].Merge = true;
            //xlSheet.Cells[dong, 1].Value = "Tổng tiền: ";

            // Sum tổng tiền
            xlSheet.Cells[dong, 4].Formula = "SUM(D6:D" + (6 + dt.Rows.Count - 1) + ")";
            xlSheet.Cells[dong, 5].Formula = "SUM(E6:E" + (6 + dt.Rows.Count - 1) + ")";

            // định dạng số
            NumberFormat(dong, 4, dong, 5, xlSheet);

            setBorder(5, 1, 5 + dt.Rows.Count, 5, xlSheet);
            setFontBold(5, 1, 5, 5, 11, xlSheet);
            setFontSize(6, 1, 6 + dt.Rows.Count, 5, 11, xlSheet);

ThongKe/ThongKe.Web/Views/BaoCao/DoanTheoNgayDi.cshtml
@{
    ViewBag.Title = "";
    Layout = "/Views/Shared/_Layout.cshtml";

    var cn = "";
    if ((Session["chinhanh"]) == null)
    {
        cn = "";
    }
    else
    {
        cn = Session["chinhanh"].ToString();
    }
    var nhom = Session["nhom"].ToString();
}

@section scripts{
    <script src="~/Assets/Admin/js/User/bootbox.min.js"></script>
    <script src="~/Assets/Admin/js/User/mustache.min.js"></script>
    <script src="~/Assets/Admin/js/User/jquery.twbsPagination.min.js"></script>
    <script src="~/Assets/Admin/js/User/jquery.validate.min.js"></script>
    <script src="~/Assets/Admin/js/User/jquery-ui/jquery-ui.js"></script>
    <script src="~/Assets/Admin/js/DoanTheoNgayDi/doanTheoNgayDiController.js"></script>
    <link href="~/Assets/Admin/css/user.css" rel="stylesheet" />
    <script>
            //$(function () {
            //    $('.modal-dialog').draggable();
            //});
      
    </script>
  
}
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>BÁO CÁO DOANH THU ĐOÀN THEO NGÀY ĐI TOUR</h4>
        </div>
        <div class="panel-body">
            <form id="frmSearch" asp-controller="BaoCao" asp-action="DoanTheoNgay" method="post" class="form-horizontal" role="form">
                <div class="row">
                    <div class="col-md-12">

                        <input type="hidden" id="hidCn" data-cn="@cn" />
                        <input type="hidden" id="hidNhom" data-nhom="@nhom" />

                        <div class="col-md-2">
                            Từ ngày
                            <input type="text" class="form-control maskInput" name="tungay" id="txtTuNgay" placeholder="Type date..." />
                        </div>

                        <div class="col-md-2">
                            Đến ngày
                            <input type="text" class="form-control maskInput" name="denngay" id="txtDenNgay" placeholder="Type date..." />
                        </div>
                        @if (nhom == "Admins" || nhom == "TNB" || nhom == "DNB" || nhom == "MT" || nhom == "MB")
                        {
                            <div class="col-md-2">
                                Code CN
                                <select class="form-control" id="ddlChiNhanh" name="cn">
                                    @*<option value="STS">STS</option>
                    <option value="STL">STL</option>*@
                                </select>
                            </div>

                            <div class="col-md-2">
                                Khối
                                <select class="form-control" id="ddlKhoi" name="khoi">
                                    <option value="OB">OB</option>
                                    <option value="ND">ND</option>
                                </select>
                            </div>
                        }
                        else
                        {

                            var khoi = Session["khoi"].ToString();
                            <input type="hidden" id="hidKhoi" data-khoi="@khoi" />
                                    }
                        <br />
                        <div class="col-md-3">

                            <span class="btn-group">
                                <button type="button" id="btnSearch" class="btn btn-outline btn-primary"><i class="fa fa-search"></i></button>
                                <button id="btnReset" class="btn btn-outline btn-warning"><i class="fas fa-broom"></i></button>
                                <button id="btnExport" class="btn btn-outline btn-success"><i class="fas fa-file-export"></i></button>
                            </span>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>
<br />

<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-hover">
            <thead>
                <tr class="text-left">
                    <td>#</td>
                    <td>STT</td>
                    <td>SGT code</td>
                    <td>Tuyen tham quan</td>
                    <td>Ngày bắt đầu</td>
                    <td>Ngày kết thúc</td>
                    <td>Số khách</td>
                    <td>Doanh số</td>

                </tr>
            </thead>
            <tbody id="tblData" class="table table-hover"></tbody>
        </table>

        <div id="pagination" class="pagination"></div>
    </div>


    <script id="data-template" type="x-tmpl-mustache">
        Hello {{ hoten }}!
        <tr>
            <td>
                <form id="frmDetail" action="/BaoCao/LoadDataDoanTheoNgayDiChitietToExcel">
                    <input type="hidden" name="sgtcode" id="hidSgtcode" />
                    <input type="hidden" name="khoi" id="hidKhoi" />
                    <button type="button" data-sgtcode="{{sgtcode}}" class="btn btn-outline btn-success btnExportDetail"><i class="fas fa-file-export"></i></button>
                </form>
            </td>
            <td class="text-center">{{stt}}</td>
            <td class="text-left">{{sgtcode}}</td>
            <td class="text-left">{{tuyentq}}</td>
            <td class="text-center">{{batdau}}</td>
            <td class="text-center">{{ketthuc}}</td>
            <td class="text-center">{{sokhach}}</td>
            <td class="text-right">{{doanhthu}}</td>

        </tr>
    </script>
</div>

ThongKe/ThongKe.Web/Views/BaoCao/KhachleHethong.cshtml
@{
    ViewBag.Title = "KhachLeHethong";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var cn = "";
    if ((Session["chinhanh"]) == null)
    {
        cn = "";
    }
    else
    {
        cn = Session["chinhanh"].ToString();
    }

    var nhom = Session["nhom"].ToString();

}


@section scripts{
    <script src="~/Assets/Admin/js/User/bootbox.min.js"></script>
    <script src="~/Assets/Admin/js/User/mustache.min.js"></script>
    <script src="~/Assets/Admin/js/User/jquery.twbsPagination.min.js"></script>
    <script src="~/Assets/Admin/js/User/jquery.validate.min.js"></script>
    <script src="~/Assets/Admin/js/User/jquery-ui/jquery-ui.js"></script>
    <script src="~/Assets/Admin/js/KhachLeHeThong/khachLeHeThongController.js"></script>
    <script src="~/Scripts/jquery.maskedinput.min.js"></script>
    <link href="~/Assets/Admin/css/user.css" rel="stylesheet" />
    @*<script>
        $(function () {
            $(".maskInput").mask("99/99/9999");
        })
        </script>*@
}
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>HIỆU QUẢ LIÊN KẾT QUẦY KHÁCH LẼ CỦA CHI NHÁNH</h4>
        </div>
        <div class="panel-body">

            <form id="frmSearch" asp-controller="BaoCao" asp-action="KhachLeHeThong" method="post" class="form-horizontal" role="form">
                <div class="row">

                    <div class="col-md-12">

                        <input type="hidden" id="hidCn" data-cn="@cn" />
                        <input type="hidden" id="hidNhom" data-nhom="@nhom" />

                        <div class="col-md-2">
                            Từ ngày
                            <input type="text" class="form-control maskInput" name="tungay" id="txtTuNgay" placeholder="Type date..." />
                        </div>

                        <div class="col-md-2">
                            Đến ngày
                            <input type="text" class="form-control maskInput" name="denngay" id="txtDenNgay" placeholder="Type date..." />
                        </div>
                        @if (nhom == "Admins" || nhom == "TNB" || nhom == "DNB" || nhom == "MT" || nhom == "MB")
                        {
                            <div class="col-md-2">
                                Code CN
                                <select class="form-control" id="ddlChiNhanh" name="cn">
                                    @*<option value="">Tất cả</option>
                    <option value="STS">STS</option>
                    <option value="STH">STH</option>*@
                                </select>
                            </div>
                            <div class="col-md-2">
                                Khối
                                <select class="form-control" id="ddlKhoi" name="khoi">
                                    <option value="OB">OB</option>
                                    <option value="ND">ND</option>
                                </select>
                            </div>
                        }
                        else
                        {

                            var khoi = Session["khoi"].ToString();
                            <input type="hidden" id="hidKhoi" data-khoi="@khoi" />
                        }
                        <br />
                        <div class="col-md-3">

                            <span class="btn-group">
                                <button type="button" id="btnSearch" class="btn btn-outline btn-primary"><i class="fa fa-search"></i></button>
                                <button id="btnReset" class="btn btn-outline btn-warning"><i class="fas fa-broom"></i></button>
                                <button id="btnExport" class="btn btn-outline btn-success"><i class="fas fa-file-export"></i></button>
                            </span>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-hover">
            <thead>
                <tr class="text-center">
                    <td>STT</td>
                    <td>Code CN</td>
                    <td>Văn phòng xuất vé</td>
                    <td>Khách ht</td>
                    <td>Thực thu ht</td>
                    <td>Khách cũ</td>
                    <td>Thực thu cũ</td>

                </tr>
            </thead>
            <tbody id="tblData" class="table table-hover"></tbody>
        </table>

        <div id="pagination" class="pagination"></div>
    </div>


    <script id="data-template" type="x-tmpl-mustache">
        Hello {{ hoten }}!
        <tr class="text-right">

            <td class="text-center">{{stt}}</td>
            <td class="text-center">{{chinhanh}}</td>
            <td class="text-left">{{dailyxuatve}}</td>
            <td class="text-center">{{khachht}}</td>
            <td>{{thucthuht}}</td>
            <td class="text-center">{{khachcu}}</td>
            <td>{{thucthucu}}</td>

        </tr>
    </script>
</div>

ThongKe/ThongKe.Web/Views/BaoCao/KinhDoanhOnline.cshtml
@{
    ViewBag.Title = "KinhDoanhOnline";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var cn = "";
    if ((Session["chinhanh"]) == null)
    {
        cn = "";
    }
    else
    {
        cn = Session["chinhanh"].ToString();
    }
    var nhom = Session["nhom"].ToString();
}

@section scripts{
    <script src="~/Assets/Admin/js/User/bootbox.min.js"></script>
    <script src="~/Assets/Admin/js/User/mustache.min.js"></script>
    <script src="~/Assets/Admin/js/User/jquery.twbsPagination.min.js"></script>
    <script src="~/Assets/Admin/js/User/jquery.validate.min.js"></script>
    <script src="~/Assets/Admin/js/User/jquery-ui/jquery-ui.js"></script>
    <script src="~/Assets/Admin/js/KinhDoanhOnline/kinhDoanhOnlineController.js"></script>
    <link href="~/Assets/Admin/css/user.css" rel="stylesheet" />
    <script>
                    //$(function () {
                    //    $('.modal-dialog').draggable();
                    //});

    </script>

}

<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>BÁO CÁO DOANH THU ĐOÀN THEO NGÀY ĐI TOUR</h4>
        </div>
        <div class="panel-body">
            <form id="frmSearch" asp-controller="BaoCao" asp-action="DoanTheoNgay" method="post" class="form-horizontal" role="form">
                <div class="row">
                    <div class="col-md-12">

                        <input type="hidden" id="hidCn" data-cn="@cn" />
                        <input type="hidden" id="hidNhom" data-nhom="@nhom" />

                        <div class="col-md-2">
                            Từ ngày
                            <input type="text" class="form-control maskInput" name="tungay" id="txtTuNgay" placeholder="Type date..." />
                        </div>

                        <div class="col-md-2">
                            Đến ngày
                            <input type="text" class="form-control maskInput" name="denngay" id="txtDenNgay" placeholder="Type date..." />
                        </div>
                        <div class="col-md-2">
                            Khối
                            <select class="form-control" id="ddlKhoi" name="khoi">
                                <option value="OB">OB</option>
                                <option value="ND">ND</option>
                            </select>
                        </div>
                        @*@if (nhom == "Admins" || nhom == "TNB" || nhom == "DNB" || nhom == "MT" || nhom == "MB")
        {
            <div class="col-md-2">
                Khối
                <select class="form-control" id="ddlKhoi" name="khoi">
                    <option value="OB">OB</option>
                    <option value="ND">ND</option>
                </select>
            </div>
        }
        else
        {

            var khoi = Session["khoi"].ToString();
            <input type="hidden" id="hidKhoi" data-khoi="@khoi" />
        }*@
                        <br />
                        <div class="col-md-3">

                            <span class="btn-group">
                                <button type="button" id="btnSearch" class="btn btn-outline btn-primary"><i class="fa fa-search"></i></button>
                                <button id="btnReset" class="btn btn-outline btn-warning"><i class="fas fa-broom"></i></button>
                                @*<button id="btnExport" class="btn btn-outline btn-success"><i class="fas fa-file-export"></i></button>*@
                            </span>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>
<br />

<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-hover">
            <thead>
                <tr class="text-center">
                    <td>#</td>
                    <td>Code CN</td>
                    <td>Tạo vé</td>
                    <td>Tự huỷ</td>
                    <td>Chưa xuất vé</td>
                    <td>Thành công</td>
                    <td>Huỷ</td>
                </tr>
            </thead>
            <tbody id="tblData" class="table table-hover"></tbody>
        </table>

        <div id="pagination" class="pagination"></div>
    </div>


    <script id="data-template" type="x-tmpl-mustache">
        Hello {{ hoten }}!
        <tr>
            <td>
                <form id="frmDetail" action="/BaoCao/LoadDataKinhDoanhOnlineChitietToExcel">
                    <input type="hidden" name="tungay" id="hidTuNgay" />
                    <input type="hidden" name="denngay" id="hidDenNgay" />
                    <input type="hidden" name="chinhanh" id="hidChiNhanh" />
                    <input type="hidden" name="khoi" id="hidKhoi" />
                    <button type="button" data-chinhanh="{{chinhanh}}" class="btn btn-outline btn-success btnExportDetail"><i class="fas fa-file-export"></i></button>

                </form>
            </td>
            <td class="text-center">{{chinhanh}}</td>
            <td class="text-center">{{taove}}</td>
            <td class="text-center">{{tuhuy}}</td>
            <td class="text-center">{{chuaxuatve}}</td>
            <td class="text-center">{{thanhcong}}</td>
            <td class="text-center">{{huy}}</td>

        </tr>
    </script>
</div>

ThongKe/ThongKe.Web/Views/BaoCao/LoadDataQuayTheoNgayBanChitietToExcel.cshtml
@model System.Data.DataTable
@using System.Data;

@{
    ViewBag.Title = "LoadDataQuayTheoNgayDiChitietToExcel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table>
    <thead>
        <tr>
            @foreach (DataColumn col in Model.Columns)
            {
                <th>@col.ColumnName</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (DataRow row in Model.Rows)
        {
            <tr>
                @foreach (DataColumn col in Model.Columns)
                {
                    <td>@row[col.ColumnName]</td>
                }
            </tr>
        }
    </tbody>
</table>

ThongKe/ThongKe.Web/Views/BaoCao/LoadDataQuayTheoNgayDiChitietToExcel.cshtml
@model System.Data.DataTable
@using System.Data;

@{
    ViewBag.Title = "LoadDataQuayTheoNgayDiChitietToExcel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table>
    <thead>
        <tr>
            @foreach (DataColumn col in Model.Columns)
            {
                <th>@col.ColumnName</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (DataRow row in Model.Rows)
        {
            <tr>
                @foreach (DataColumn col in Model.Columns)
                {
                    <td>@row[col.ColumnName]</td>
                }
            </tr>
        }
    </tbody>
</table>

ThongKe/ThongKe.Web/Views/BaoCao/NgayBan.cshtml
@{
    ViewBag.Title = "NgayCN";
    Layout = "/Views/Shared/_Layout.cshtml";

}

@section scripts{
    <script src="~/Assets/Admin/js/User/bootbox.min.js"></script>
    <script src="~/Assets/Admin/js/User/mustache.min.js"></script>
    <script src="~/Assets/Admin/js/User/jquery.twbsPagination.min.js"></script>
    <script src="~/Assets/Admin/js/User/jquery.validate.min.js"></script>
    <script src="~/Assets/Admin/js/User/jquery-ui/jquery-ui.js"></script>
    <script src="~/Assets/Admin/js/NgayBan/ngayBanController.js"></script>
    <link href="~/Assets/Admin/css/user.css" rel="stylesheet" />
    @*<script>
            $(function () {
                $('.modal-dialog').draggable();
            });
        </script>*@
}

<br />
<form id="frmSearch" asp-controller="BaoCao" asp-action="NgayBan" method="get" class="form-horizontal" role="form">
    <div class="row">
        <div class="col-md-12">

            <div class="col-md-4">
                Từ ngày
                <input type="text" class="form-control" name="tungay" id="txtTuNgay" placeholder="Type date..." />
            </div>

            <div class="col-md-4">
                Dến ngày
                    <input type="text" class="form-control" name="denngay" id="txtDenNgay" placeholder="Type date..." />
                    
            </div>
            <br />
            <div class="col-md-2">
                <span class="btn-group">
                    <button id="btnSearch" class="btn btn-outline btn-primary"><i class="fa fa-search"></i></button>
                    <button id="btnReset" class="btn btn-outline btn-default">Reset</button>
                </span>
            </div>

        </div>
    </div>
</form>
<br />